#pragma once

#include <stdint.h>
#include <sb_types.h>

// Do not edit this file as it will be overwritten if codegen is rerun

bool get_read_port(int32_t *data);
bool put_write_port(const int32_t *data);
