# This work is Crown Copyright NCSC, 2024.

# Add any additional files or configurations for the example
CLIENT_OBJS = empty_client.o
CLIENT_INC := empty_client
CLIENT_CFLAGS :=
CLIENT_LDFLAGS :=
CLIENT_LIBS :=
CLIENT_WARNINGS := 


