# This work is Crown Copyright NCSC, 2024.

# Add any additional files or configurations for the example
CLIENT_OBJS = moving_square.o
CLIENT_INC := examples/moving_square
CLIENT_CFLAGS :=
CLIENT_LDFLAGS :=
CLIENT_LIBS :=
CLIENT_WARNINGS := 

