name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_examples_linux_x86_64:
    name: Build example systems (Linux x86-64 via apt)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout LionsOS repository
        uses: actions/checkout@v4
      - name: Download Microkit SDK
        run: |
          wget https://github.com/seL4/microkit/releases/download/1.4.1/microkit-sdk-1.4.1-linux-x86-64.tar.gz
          tar xf microkit-sdk-1.4.1-linux-x86-64.tar.gz
      - name: Download and install AArch64 GCC toolchain
        run: |
          wget -O aarch64-toolchain.tar.gz https://trustworthy.systems/Downloads/microkit/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf.tar.xz
          tar xf aarch64-toolchain.tar.gz
          echo "$(pwd)/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/bin" >> $GITHUB_PATH
      - name: Install dependencies (apt)
        run: |
          sudo apt update && sudo apt install make cmake clang lld llvm device-tree-compiler qemu-system-arm
      - name: Run examples script
        run: ./ci/examples.sh $(pwd) $(pwd)/microkit-sdk-1.4.1
  build_examples_linux_x86_64_nix:
    name: Build example systems (Linux x86-64 via Nix)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout LionsOS repository
        uses: actions/checkout@v4
      - name: Download Microkit SDK
        run: |
          wget https://github.com/seL4/microkit/releases/download/1.4.1/microkit-sdk-1.4.1-linux-x86-64.tar.gz
          tar xf microkit-sdk-1.4.1-linux-x86-64.tar.gz
      - name: Download and install AArch64 GCC toolchain
        run: |
          wget -O aarch64-toolchain.tar.gz https://trustworthy.systems/Downloads/microkit/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf.tar.xz
          tar xf aarch64-toolchain.tar.gz
          echo "$(pwd)/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/bin" >> $GITHUB_PATH
      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Run examples script
        run: nix-shell --run "./ci/examples.sh $(pwd) $(pwd)/microkit-sdk-1.4.1"
  build_examples_macos_aarch64_nix:
    name: Build example systems (macOS ARM64 via Nix)
    runs-on: [self-hosted, macos, ARM64]
    steps:
      - name: Checkout LionsOS repository
        uses: actions/checkout@v4
        with:
          submodules: true
      # Because we use self-hosted actions and the checkout action does not clean submodules
      # we need to manually clean the submodules of the repo.
      - name: Clean submodules
        run: |
          git submodule foreach --recursive git clean -ffdx
          git submodule foreach --recursive git reset --hard
      - name: Download Microkit SDK
        run: |
          wget https://github.com/seL4/microkit/releases/download/1.4.1/microkit-sdk-1.4.1-macos-aarch64.tar.gz
          tar xf microkit-sdk-1.4.1-macos-aarch64.tar.gz
      - name: Download and install AArch64 GCC toolchain
        run: |
          wget -O aarch64-toolchain.tar.gz https://trustworthy.systems/Downloads/microkit/arm-gnu-toolchain-12.3.rel1-darwin-arm64-aarch64-none-elf.tar.xz
          tar xf aarch64-toolchain.tar.gz
          echo "$(pwd)/arm-gnu-toolchain-12.3.rel1-darwin-arm64-aarch64-none-elf/bin" >> $GITHUB_PATH
      - name: Run examples script
        run: nix-shell --run "./ci/examples.sh $(pwd) $(pwd)/microkit-sdk-1.4.1"
