name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_kitty_linux_x86_64:
    name: Build Kitty example (Linux x86-64)
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout LionsOS repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Download Microkit SDK
        run: ./ci/acquire_sdk.sh microkit-sdk.zip ${{ secrets.GITHUB_TOKEN }} linux-x86-64
        shell: bash
      - name: Extract Microkit SDK
        run: unzip microkit-sdk.zip && tar -xf microkit-sdk-1.2.6.tar.gz
      - name: Download and install AArch64 GCC toolchain
        run: |
          wget -O aarch64-toolchain.tar.gz https://trustworthy.systems/Downloads/microkit/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf.tar.xz
          tar xf aarch64-toolchain.tar.gz
          echo "$(pwd)/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/bin" >> $GITHUB_PATH
      - name: Build Kitty example
        run: export LIBGCC=$(pwd)/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/lib/gcc/aarch64-none-elf/12.3.1 && make -C examples/kitty MICROKIT_SDK=$(pwd)/microkit-sdk-1.2.6
        env:
          NFS_SERVER: 0.0.0.0
          NFS_DIRECTORY: test/
  build_kitty_macos_aarch64:
    name: Build Kitty example (macOS ARM64)
    runs-on: [self-hosted, macos, ARM64]
    steps:
      - name: Checkout LionsOS repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Download Microkit SDK
        run: nix-shell -p jq --run "./ci/acquire_sdk.sh microkit-sdk.zip ${{ secrets.GITHUB_TOKEN }} macos-aarch64"
        shell: bash
      - name: Extract Microkit SDK
        run: unzip microkit-sdk.zip && tar -xf microkit-sdk-1.2.6.tar.gz
      - name: Download and install AArch64 GCC toolchain
        run: |
          wget -O aarch64-toolchain.tar.gz https://trustworthy.systems/Downloads/microkit/arm-gnu-toolchain-12.3.rel1-darwin-arm64-aarch64-none-elf.tar.xz
          tar xf aarch64-toolchain.tar.gz
          echo "$(pwd)/arm-gnu-toolchain-12.3.rel1-darwin-arm64-aarch64-none-elf/bin" >> $GITHUB_PATH
      - name: Build Kitty example
        run: export LIBGCC=$(pwd)/arm-gnu-toolchain-12.3.rel1-darwin-arm64-aarch64-none-elf/lib/gcc/aarch64-none-elf/12.3.1 && nix-shell --run 'make -C examples/kitty MICROKIT_SDK=$(pwd)/microkit-sdk-1.2.6'
        env:
          NFS_SERVER: 0.0.0.0
          NFS_DIRECTORY: test/
