name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_kitty_linux_x86_64:
    name: Build Kitty example (Linux x86-64)
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout KISS repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Download Microkit SDK
        run: ./ci/acquire_sdk.sh microkit-sdk.zip ${{ secrets.GITHUB_TOKEN }} linux-x86-64
        shell: bash
      - name: Extract Microkit SDK
        run: unzip microkit-sdk.zip && tar -xf microkit-sdk-1.2.6.tar.gz
      - name: Build Kitty example
        run: nix-shell --pure --run "make -C examples/kitty MICROKIT_SDK=$(pwd)/microkit-sdk-1.2.6"

