name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_kitty_linux_x86_64:
    name: Build Kitty example (Linux x86-64)
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout LionsOS repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Download Microkit SDK
        run: wget https://trustworthy.systems/Downloads/microkit/microkit-sdk-dev-8e40fe8-linux-x86-64.tar.gz
      - name: Extract Microkit SDK
        run: tar -xf microkit-sdk-dev-8e40fe8-linux-x86-64.tar.gz
      - name: Download and install AArch64 GCC toolchain
        run: |
          wget -O aarch64-toolchain.tar.gz https://trustworthy.systems/Downloads/microkit/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf.tar.xz
          tar xf aarch64-toolchain.tar.gz
          echo "$(pwd)/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/bin" >> $GITHUB_PATH
      - name: Build Kitty example
        run: make -C examples/kitty MICROKIT_SDK=$(pwd)/microkit-sdk-1.2.6
        env:
          LIBGCC: ${PWD}/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/lib/gcc/aarch64-none-elf/12.3.1
          LIBMATH: ${PWD}/arm-gnu-toolchain-12.3.rel1-x86_64-aarch64-none-elf/aarch64-none-elf/lib/
          NFS_SERVER: 0.0.0.0
          NFS_DIRECTORY: test/
  build_kitty_macos_aarch64:
    name: Build Kitty example (macOS ARM64)
    runs-on: [self-hosted, macos, ARM64]
    steps:
      - name: Checkout LionsOS repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Download Microkit SDK
        run: wget https://trustworthy.systems/Downloads/microkit/microkit-sdk-dev-8e40fe8-macos-aarch64.tar.gz
      - name: Extract Microkit SDK
        run: tar -xf microkit-sdk-dev-8e40fe8-macos-aarch64.tar.gz
      - name: Download and install AArch64 GCC toolchain
        run: |
          wget -O aarch64-toolchain.tar.gz https://trustworthy.systems/Downloads/microkit/arm-gnu-toolchain-12.3.rel1-darwin-arm64-aarch64-none-elf.tar.xz
          tar xf aarch64-toolchain.tar.gz
          echo "$(pwd)/arm-gnu-toolchain-12.3.rel1-darwin-arm64-aarch64-none-elf/bin" >> $GITHUB_PATH
      - name: Build Kitty example
        run: nix-shell --run 'make -C examples/kitty MICROKIT_SDK=$(pwd)/microkit-sdk-1.2.6'
        env:
          LIBGCC: ${PWD}/arm-gnu-toolchain-12.3.rel1-darwin-arm64-aarch64-none-elf/lib/gcc/aarch64-none-elf/12.3.1
          LIBMATH: ${PWD}/arm-gnu-toolchain-12.3.rel1-darwin-arm64-aarch64-none-elf/aarch64-none-elf/lib/
          NFS_SERVER: 0.0.0.0
          NFS_DIRECTORY: test/
