name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build_kitty_linux_x86_64:
    name: Build Kitty example (Linux x86-64)
    runs-on: [self-hosted, linux, x64]
    steps:
      - name: Checkout KISS repository
        uses: actions/checkout@v3
        with:
          submodules: 'true'
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Download seL4CP SDK
        run: ./ci/acquire_sdk.sh sel4cp-sdk.zip ${{ secrets.GITHUB_TOKEN }} linux-x86-64
        shell: bash
      - name: Extract seL4CP SDK
        run: unzip sel4cp-sdk.zip && tar -xf sel4cp-sdk-1.2.6.tar.gz
      - name: Build Kitty example
        run: nix-shell --pure --run "make -C examples/kitty SEL4CP_SDK=$(pwd)/sel4cp-sdk-1.2.6"
